### ISSUE TITLE
train

### ISSUE THREAD

**Issue by xiaoyaod** [feiaxyt/EMC-Click#2]
训练的时候需不需要两阶段？

**Comment by xiaoyaod** [comment]
就是先训练Base Segmentation Network  然后冻结Base Segmentation Network 再训练Mask Correction Network

**Comment by feiaxyt** [comment]
> 就是先训练Base Segmentation Network 然后冻结Base Segmentation Network 再训练Mask Correction Network

不需要两阶段，两个网络可以同时训练
