### ISSUE TITLE
About prepare first click input for the base segmentation network

### ISSUE THREAD

**Issue by SIQI9747** [feiaxyt/EMC-Click#3]
Dear author, thant you for you great work.

I have a quick question regarding to preparing the input for the base segmentation work. 

In the paper figure2, it seems the first click embeding is ADDED to the image instead of concatenated? Then does the conv block after first click mean to change the first click dimension, so that it can added to image?

**Comment by feiaxyt** [comment]
Yes. This is the same with RITM.

**Comment by SIQI9747** [comment]
@feiaxyt Thanks for the reply. Got it
